source 'https://rubygems.org'
ruby '1.9.3'
gem 'rspec',           '2.11.0'
gem 'chefspec',        '1.3.1'
gem 'chef',            '11.4.4'
gem 'knife-rackspace', '0.7.0'
gem 'knife-ec2'
gem 'fog'
gem 'json'
gem 'rspec-mocks'
