include_recipe "country_customisations_centos::clone_configuration_repo"
include_recipe "country_customisations_centos::customise_localsettings"
include_recipe "country_customisations_centos::configure_registration_messages"
